import { HandlerFn, Injector, Invocation, OnDestroy } from '@tsdi/ioc';
import { Pattern, PatternFormatter, RequestHandler, Transport, RequestContext, ReadableLike, Incoming } from '@tsdi/common';
import { Observable } from 'rxjs';
import { AbstractRequestContext } from '../AbstractRequestContext';
import { AssetRoute, Route, Routes } from './route';
import { RouteHanlder, RoutePatterns, Router } from './router';
import { TrieOptions, Wlidcard } from './trie';
export declare class OptimizedRouter extends Router<RouteHanlder> implements OnDestroy {
    private injector;
    readonly formatter: PatternFormatter;
    readonly prefix: string;
    readonly transport: Transport | null;
    private microservice?;
    private trieRouter;
    private cache;
    private params;
    private regExps;
    private regCache;
    private assets;
    private _routes;
    get routes(): Routes;
    readonly options: TrieOptions;
    constructor(injector: Injector, formatter: PatternFormatter, prefix?: string, transport?: Transport | null, options?: Partial<TrieOptions>, routes?: Routes, microservice?: boolean | undefined);
    use(asset: AssetRoute): this;
    use(route: Route): this;
    use(route: Pattern, handler: RouteHanlder, callback?: (route: Route) => void): this;
    unuse(route: Route): this;
    getPatterns(): RoutePatterns;
    handle(req: ReadableLike<Incoming>, context: RequestContext): Observable<any>;
    intercept(req: ReadableLike<Incoming>, next: RequestHandler<ReadableLike<Incoming>>, context: RequestContext): Observable<any>;
    doHandle(req: ReadableLike<Incoming>, context: RequestContext, notFound?: () => Observable<any>): Observable<any>;
    protected load(route: Route): Promise<Routes>;
    protected parseCtrl(invocation: Invocation, prefix: string, pathParams: any): Routes;
    protected parse(route: Route): HandlerFn | undefined;
    getRoute(req: ReadableLike<Incoming>, context: RequestContext): Promise<Route | undefined>;
    private initPaths;
    onDestroy(): void;
    protected redirect(ctx: AbstractRequestContext, url: string, alt?: string): Promise<any>;
}
export declare function matchWildcard(wlidcard: string, match: 'start' | 'end' | 'equals' | 'startEnd' | 'startWith' | ((part: string, parts: string[], index: number) => boolean), toPath?: (part: string) => string): Wlidcard;
export declare function matchWildcard(wlidcard: string, match: 'start' | 'end' | 'equals' | 'startEnd' | 'startWith' | ((part: string, parts: string[], index: number) => boolean), mutil?: boolean, includeParent?: boolean, toPath?: (part: string) => string): Wlidcard;
