import { ApplicationArguments, AppMode, AppPlatform } from '@tsdi/core';
export declare class ServerApplicationArguments extends ApplicationArguments {
    private _env;
    private _source;
    private _signls;
    private _args;
    private _cmds?;
    private _name;
    private _version;
    private _mode;
    private _platform;
    private _cwd;
    private _hostname;
    private _pid;
    private _locale;
    private _timezone;
    private _debug;
    private _logLevel;
    private _baseURL;
    private _envOverride;
    constructor(_env: Record<string, string | undefined>, _source: string[]);
    protected initEnvironment(): void;
    protected resolveEnv(key: string, defaultValue: string): string;
    protected resolveMode(): AppMode;
    protected resolveDebug(): boolean;
    get env(): Record<string, string | undefined>;
    get argsSource(): string[];
    get args(): Record<string, string>;
    get cmds(): string[];
    get signls(): string[];
    get name(): string;
    get version(): string;
    get mode(): AppMode;
    get platform(): AppPlatform;
    get cwd(): string;
    get hostname(): string;
    get pid(): number;
    get locale(): string;
    get timezone(): string;
    get debug(): boolean;
    get logLevel(): string;
    get baseURL(): string;
    reset(args: string[]): void;
    mergeEnvironment(env: Partial<ApplicationArguments>): void;
    protected toRecord(args: string[]): Record<string, string | boolean | number>;
    protected tryGetSignls(): string[];
}
