import { Invocation, Token } from '@tsdi/ioc';
import { GuardLike, VaildatorLike } from '@tsdi/core';
import { RequestInterceptorLike, RequestHandlerLike, RequestFilterLike, Outgoing, Incoming, RequestContext } from '@tsdi/common';
import { ServiceConfig } from './server.options';
import { Router } from './router/router';
import { ServiceHandler } from './ServiceHandler';
import { MiddlewareLike } from './middleware/middleware';
export declare const RESPONSE: import("@tsdi/ioc").InjectToken<Outgoing<any, any>>;
export declare function getGuardsToken(config: ServiceConfig): Token<GuardLike[]>;
export declare function getFiltersToken(config: ServiceConfig): Token<RequestFilterLike[]>;
export declare function getRequestVaildatorsToken(config: ServiceConfig): Token<VaildatorLike<Incoming, RequestContext>[]>;
export declare function getResponseVaildatorsToken(config: ServiceConfig): Token<VaildatorLike<Outgoing, RequestContext>[]>;
export declare function getInterceptorsToken(config: ServiceConfig): Token<RequestInterceptorLike[]>;
export declare function getMiddlewaresToken(config: ServiceConfig): Token<MiddlewareLike[]>;
export declare function getTransfersToken(config: ServiceConfig): Token<RequestInterceptorLike[]>;
export declare function getRouterToken(config: ServiceConfig): Token<Router>;
export declare function getServiceOptionsToken(config: ServiceConfig): Token<ServiceConfig>;
export declare function getServiceHandlerToken(config: ServiceConfig): Token<ServiceHandler>;
export declare function getServiceBackendToken(config: ServiceConfig): Token<RequestHandlerLike>;
export declare function getServiceToken<T>(config: ServiceConfig): Token<Invocation<T>>;
