import { ResolveInterceptorFn, Provider, Type } from '@tsdi/ioc';
import { NodeInjector } from '../refs/injector';
import { DirectiveRef } from '../refs/directive';
import { ComponentRef } from '../refs/component';
export declare const elementRefResovler: ResolveInterceptorFn;
export declare const templateRefResovler: ResolveInterceptorFn;
export declare const directorRefResovler: ResolveInterceptorFn;
export declare const componentRefResovler: ResolveInterceptorFn;
export declare const viewContainerRefResovler: ResolveInterceptorFn;
export declare const directorResovler: ResolveInterceptorFn;
export declare function resolveDirectiveFromNode(injector: NodeInjector, node: any, directiveType: Type): DirectiveRef<any> | null;
export declare function resolveComponentFromNode(injector: NodeInjector, node: any, componentType: Type): ComponentRef<any> | null;
export declare const componentResolvers: Provider[];
