import { Header, HeaderAdapter, HeadersLike, IHeaders } from './headers';
export declare class DefaultHeaderAdapter implements HeaderAdapter {
    hasHeader(headers: HeadersLike, header: string): boolean;
    getHeader<T = number | string>(headers: HeadersLike, header: string, join?: boolean): T | undefined;
    getHeaders(headers: HeadersLike): IHeaders;
    setHeader<T extends HeadersLike>(headers: T, header: string, value: Header): T;
    removeHeader<T extends HeadersLike>(headers: T, header: string): T;
    removeHeaders<T extends HeadersLike>(headers: T): T;
    hasContentType(headers: HeadersLike): boolean;
    getContentType(headers: HeadersLike): string;
    setContentType<T extends HeadersLike>(headers: T, type: string | null | undefined): T;
    hasContentLength(headers: HeadersLike): boolean;
    setContentLength<T extends HeadersLike>(headers: T, len: number | null | undefined): T;
    getContentLength(headers: HeadersLike): number;
    hasContentEncoding(headers: HeadersLike): boolean;
    getContentEncoding(headers: HeadersLike): string | undefined;
    setContentEncoding<T extends HeadersLike>(headers: T, encoding: string | null): T;
    getContentDisposition(headers: HeadersLike): string | undefined;
    setContentDisposition<T extends HeadersLike>(headers: T, disposition: string | null): T;
    hasTransferEncoding(headers: HeadersLike): boolean;
    getTransferEncoding(headers: HeadersLike): string | undefined;
    setTransferEncoding<T extends HeadersLike>(headers: T, encoding: string | null | undefined): T;
    getIdentity(headers: HeadersLike): string | number | undefined;
    setIdentity<T extends HeadersLike>(headers: T, identity: string | number | undefined): T;
    getMethod(headers: HeadersLike, prefix?: boolean): string | undefined;
    setMethod<T extends HeadersLike>(headers: T, method: string | undefined, prefix?: boolean): T;
    getPath(headers: HeadersLike, prefix?: boolean): string | undefined;
    setPath<T extends HeadersLike>(headers: T, path: string | undefined, prefix?: boolean): T;
    getStatus(headers: HeadersLike, prefix?: boolean): string | number | undefined;
    setStatus<T extends HeadersLike>(headers: T, status: string | number, prefix?: boolean): T;
    getStatusMessage(headers: HeadersLike): string | undefined;
    setStatusMessage<T extends HeadersLike>(headers: T, statusMessage: string | undefined): T;
    getAccept(headers: HeadersLike): string | string[] | undefined;
    setAccept<T extends HeadersLike>(headers: T, accept: string | string[] | undefined): T;
    getAcceptCharset(headers: HeadersLike): string | undefined;
    setAcceptCharset<T extends HeadersLike>(headers: T, charset: string | undefined): T;
    getAcceptEncoding(headers: HeadersLike): string | undefined;
    setAcceptEncoding<T extends HeadersLike>(headers: T, encodings: string | undefined): T;
    getAcceptLanguage(headers: HeadersLike): string | undefined;
    setAcceptLanguage<T extends HeadersLike>(headers: T, languages: string | undefined): T;
    getLastModified(headers: HeadersLike): string | undefined;
    setLastModified<T extends HeadersLike>(headers: T, modified: string | undefined): T;
    getCacheControl(headers: HeadersLike): string | undefined;
    setCacheControl<T extends HeadersLike>(headers: T, control: string | undefined): T;
    getLocation(headers: HeadersLike): string | undefined;
    setLocation<T extends HeadersLike>(headers: T, location: string | undefined): T;
}
