import { Context } from '../context';
import { HandlerFn } from '../handlers/handler';
import { InterceptorLike } from '../handlers/interceptor';
import { InjectorRecord } from '../injector';
import { ClassRef } from '../metadata/class';
import { Runtime } from '../runtime';
import { RuntimeHandler } from '../lifescope/handler';
import { IocContext } from '../lifescope/context';
export declare const autorunInterceptor: (input: ClassRef, next: HandlerFn, context: IocContext) => any;
export declare function getDesignBeforeAnnoationScope(runtime: Runtime): RuntimeHandler<ClassRef, any, IocContext>;
export declare function getDesignAfterAnnoationScope(runtime: Runtime): RuntimeHandler<ClassRef, any, IocContext>;
export declare function getDesignPropertyScope(runtime: Runtime): RuntimeHandler<ClassRef, any, IocContext>;
export declare function getDesignMethodScope(runtime: Runtime): RuntimeHandler<ClassRef, any, IocContext>;
export declare const afterPropertyAnnoationInterceptor: (input: ClassRef, next: HandlerFn, context: IocContext) => any;
export declare const afterMethodAnnoationInterceptor: (input: ClassRef, next: HandlerFn, context: IocContext) => any;
export declare const afterAnnoationInterceptor: (input: ClassRef, next: HandlerFn, context: IocContext) => any;
export declare const beforeAnnoactionInterceptor: (input: ClassRef, next: HandlerFn, context: IocContext) => any;
export declare const dependencyInterceptor: (input: ClassRef, next: HandlerFn, context: IocContext) => any;
export declare const exportsInterceptor: (input: ClassRef, next: HandlerFn, context: IocContext) => any;
export declare const DESIGN_INTERECPTORS: InterceptorLike<ClassRef, InjectorRecord, Context>[];
