import { Abstract } from '@tsdi/ioc';

/**
 * Lifecycle state of a persisted parent -> child session edge. Edges start as
 * `active` when the child session is registered and transition once the child
 * turn unwinds: `completed` on success, `failed` on error, `cancelled` when the
 * parent (or an ancestor) cancelled the child turn.
 */
export type DelegationEdgeStatus = 'active' | 'completed' | 'failed' | 'cancelled';

/**
 * A persisted delegation edge linking a parent (main) session to a spawned
 * child (sub-agent) session. The runtime tracks this hierarchy in memory via
 * {@link AgentRuntime.registerChildSession} so parent cancellation cascades to
 * children; this record is the durable form of the same link so the UI can
 * render cross-task worker lineage and parent-child task trees across restarts.
 */
export interface DelegationEdgeRecord {
    id: string;
    parentSessionId: string;
    childSessionId: string;
    /** Origin of the link, e.g. `nested`, `spawn_agent`, `parallel`. */
    kind?: string;
    status: DelegationEdgeStatus;
    createdAt: number;
    /** Set when the child session unregistered or was cancelled. */
    completedAt?: number;
    /** Spawner context: goal, toolsets, model, max turns, task ids, ... */
    metadata?: Record<string, any>;
}

/**
 * Append input. `id` and `createdAt` are generated by the store when omitted so
 * every implementation stamps consistent values.
 */
export interface DelegationEdgeInput {
    id?: string;
    parentSessionId: string;
    childSessionId: string;
    kind?: string;
    status?: DelegationEdgeStatus;
    createdAt?: number;
    completedAt?: number;
    metadata?: Record<string, any>;
}

/**
 * One node of the persisted delegation tree. The root carries only its session
 * id; every child node also carries the edge that produced it so the console
 * can render kind, status, timestamps, and spawner metadata inline.
 */
export interface DelegationTreeNode {
    sessionId: string;
    edgeId?: string;
    kind?: string;
    status?: DelegationEdgeStatus;
    createdAt?: number;
    completedAt?: number;
    metadata?: Record<string, any>;
    children: DelegationTreeNode[];
}

export interface DelegationTreeOptions {
    /** Only include edges with one of the given statuses (default: all). */
    status?: DelegationEdgeStatus | DelegationEdgeStatus[];
    /** Maximum depth below the root (default: unlimited). */
    depth?: number;
}

/**
 * Shared tree builder used by every store implementation so in-memory and
 * TypeORM trees behave identically. Walks edges from `rootSessionId` downward,
 * sorting siblings by creation time, and optionally prunes by status or depth.
 */
export function buildDelegationTree(
    edges: DelegationEdgeRecord[],
    rootSessionId: string,
    options?: DelegationTreeOptions
): DelegationTreeNode {
    const statuses = normalizeStatuses(options?.status);
    const depth = Number.isFinite(options?.depth) && (options?.depth as number) >= 0
        ? Math.floor(options?.depth as number)
        : undefined;
    const byParent = new Map<string, DelegationEdgeRecord[]>();
    for (const edge of edges) {
        if (statuses && !statuses.includes(edge.status)) {
            continue;
        }
        const group = byParent.get(edge.parentSessionId) ?? [];
        group.push(edge);
        byParent.set(edge.parentSessionId, group);
    }
    for (const group of byParent.values()) {
        group.sort((left, right) => left.createdAt - right.createdAt || left.id.localeCompare(right.id));
    }
    const visit = (sessionId: string, visited: Set<string>, remainingDepth?: number): DelegationTreeNode => {
        const node: DelegationTreeNode = { sessionId, children: [] };
        if (remainingDepth === 0) {
            return node;
        }
        const nextVisited = new Set(visited);
        nextVisited.add(sessionId);
        const children = byParent.get(sessionId) ?? [];
        for (const edge of children) {
            if (nextVisited.has(edge.childSessionId)) {
                continue;
            }
            node.children.push({
                sessionId: edge.childSessionId,
                edgeId: edge.id,
                kind: edge.kind,
                status: edge.status,
                createdAt: edge.createdAt,
                completedAt: edge.completedAt,
                metadata: edge.metadata,
                children: visit(edge.childSessionId, nextVisited, remainingDepth === undefined ? undefined : remainingDepth - 1).children
            });
        }
        return node;
    };
    return visit(rootSessionId, new Set(), depth);
}

/**
 * Shared lineage builder: walks edges upward from `childSessionId` to the root
 * session, newest edge first. Returns an empty array when the child session has
 * no recorded parent, or a cycle is detected.
 */
export function buildDelegationLineage(edges: DelegationEdgeRecord[], childSessionId: string): DelegationEdgeRecord[] {
    const byChild = new Map<string, DelegationEdgeRecord>();
    for (const edge of edges) {
        byChild.set(edge.childSessionId, edge);
    }
    const lineage: DelegationEdgeRecord[] = [];
    const seen = new Set<string>();
    let current = childSessionId;
    let guard = 0;
    while (current && !seen.has(current) && guard++ < 1024) {
        seen.add(current);
        const edge = byChild.get(current);
        if (!edge) {
            break;
        }
        lineage.push(edge);
        current = edge.parentSessionId;
    }
    return lineage;
}

function normalizeStatuses(status?: DelegationEdgeStatus | DelegationEdgeStatus[]): DelegationEdgeStatus[] | undefined {
    if (!status) {
        return undefined;
    }
    const list = Array.isArray(status) ? status : [status];
    return list.length > 0 ? Array.from(new Set(list)) : undefined;
}

/**
 * Persistent store for delegation edges, mirroring the {@link AuditSink} /
 * {@link TurnDiagnosticsStore} pattern: an abstract contract with in-memory,
 * TypeORM, and environment-aware default implementations. Persistence is
 * best-effort and must never break turn execution.
 */
@Abstract()
export abstract class DelegationGraphStore {
    /** Persist a new edge (default status `active`). Returns the stored record. */
    abstract append(edge: DelegationEdgeInput): Promise<DelegationEdgeRecord>;
    /**
     * Close a previously recorded edge. Idempotent: the first close wins, so a
     * `cancelled` mark from cascade cancellation is not overwritten by the
     * child runner's later `failed` close.
     */
    abstract markClosed(parentSessionId: string, childSessionId: string, status?: DelegationEdgeStatus, completedAt?: number): Promise<void>;
    /** Direct child edges of a session, oldest first. */
    abstract children(parentSessionId: string, options?: { status?: DelegationEdgeStatus | DelegationEdgeStatus[]; limit?: number }): Promise<DelegationEdgeRecord[]>;
    /** Edges from `childSessionId` up to the root session, closest first. */
    abstract ancestors(childSessionId: string, options?: { limit?: number }): Promise<DelegationEdgeRecord[]>;
    /** Nested delegation tree rooted at `parentSessionId`. */
    abstract tree(parentSessionId: string, options?: DelegationTreeOptions): Promise<DelegationTreeNode>;
    /** Flat edge listing, optionally scoped to edges touching `sessionId`. */
    abstract list(options?: { sessionId?: string; limit?: number; offset?: number }): Promise<DelegationEdgeRecord[]>;
}
